/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/galleries/{id}/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate and "send" a 6-digit OTP for a gallery
         * @description Generates a fresh 6-digit code, stores it in `otp_codes` with
         *     `expires_at = now + 10 min`, and logs it to backend stdout in the form
         *     `[OTP] Gallery <id>: <code> (expires in 10 min)`.
         *
         *     Re-requesting an OTP for the same gallery marks any prior unused codes
         *     for that gallery as used, so only one code is valid at a time.
         *
         *     No request body. Returns only the expiry window — the code itself is
         *     never returned over the wire.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["GalleryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Code generated and logged. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Seconds until the code expires.
                             * @example 600
                             */
                            expires_in: number;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP code and receive a session token
         * @description Validates the code against `otp_codes` for the given gallery. The code
         *     must be: unused, not expired, and exactly the most recently issued
         *     code for this gallery.
         *
         *     On success: marks the code used, mints a fresh opaque bearer token
         *     (`secrets.token_urlsafe(32)`), stores it in `sessions` with
         *     `expires_at = now + 10 min` and `gallery_id` scoped to this gallery,
         *     then returns it.
         *
         *     On any failure (wrong code, expired, already used, no code exists for
         *     this gallery) returns 401 with `error: invalid_code`. The 401 does not
         *     distinguish between these cases — no enumeration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["GalleryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 482910 */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Session minted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Opaque bearer token. Send on subsequent requests as
                             *     `Authorization: Bearer <token>`. Scoped to the gallery
                             *     the token was issued for.
                             * @example k3yT2tQq8x...
                             */
                            token: string;
                            /**
                             * @description Seconds until the session expires.
                             * @example 600
                             */
                            expires_in: number;
                        };
                    };
                };
                401: components["responses"]["InvalidCode"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return gallery metadata and photo list
         * @description Returns the gallery and its photos with per-photo favorite state for
         *     the current session. Requires a bearer token issued for THIS gallery
         *     — a token issued for `g_001` will receive 401 when used against
         *     `g_002`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["GalleryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gallery view. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Gallery"];
                    };
                };
                401: components["responses"]["ExpiredSession"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{id}/favourite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle the favorite flag on a photo
         * @description Toggles `is_favorite` for the given photo within this gallery and
         *     returns the new state. The photo must belong to this gallery — a
         *     photo from `g_002` cannot be favorited via `g_001`'s session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["GalleryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example p_001 */
                        photo_id: string;
                    };
                };
            };
            responses: {
                /** @description New favorite state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example p_001 */
                            photo_id: string;
                            /** @example true */
                            is_favorite: boolean;
                        };
                    };
                };
                401: components["responses"]["ExpiredSession"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Gallery: {
            /** @example g_001 */
            id: string;
            /** @example Anna's Wedding */
            title: string;
            photos: components["schemas"]["Photo"][];
        };
        Photo: {
            /** @example p_001 */
            id: string;
            /**
             * @description Server-relative URL to the thumbnail.
             * @example /static/photos/p_001.jpg
             */
            thumbnail_url: string;
            /**
             * @description Server-relative URL to the full-size image. For v1 this is the
             *     same file as the thumbnail; the field exists so a future
             *     click-to-enlarge interaction has somewhere to point.
             * @example /static/photos/p_001.jpg
             */
            full_url: string;
            /** @example false */
            is_favorite: boolean;
        };
        Error: {
            /** @enum {string} */
            error: "invalid_code" | "expired_session" | "not_found";
        };
    };
    responses: {
        /** @description Code is wrong, expired, used, or absent. */
        InvalidCode: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "invalid_code"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, malformed, expired, or wrong-gallery bearer token. */
        ExpiredSession: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "expired_session"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Gallery or photo does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not_found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GalleryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
